language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
before_install:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.example config/database.yml
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
env:
  - MAILBOT_ENV=test
