development:
  host: 'localhost'
  adapter: 'mysql2'
  encoding: 'utf8'
  database: 'mailbot_development'
  username: 'root'
  password: 'master'

production:
  host: 'localhost'
  adapter: 'mysql2'
  encoding: 'utf8'
  database: 'mailbot_production'
