twitch:
  rest_api_root: https://api.twitch.tv/kraken
  username: OpenMailbot
  client_id: ***REMOVED***
discord:
  client_id: '***REMOVED***'
  kadgar:
    discord_channel: '342737052703391765'
    twitch_ids:
      - '133652118'  # open_mailbox
      - '122233584'  # spazee_mcgee
      - '83111366'   # jeeeeeeeef
      - '61328956'   # harl3m_struggl3
      - '79397878'   # generalandrews1_0
      - '68442684'   # flibbityflam
      - '118029540'  # job_for_a_cody
      - '69300188'   # thebossguy11
      - '141540943'  # theatakapa
      - '123616230'  # univarseman
      - '36838233'   # dariusknight
      - '20921990'   # anubisvylok
      - '90252824'   # elevatesora
      - '49623984'   # captainredwolf
      - '139605001'  # the_official_tgk
      - '145025615'  # cosmic_gamers
      - '144366639'  # soxygamer
      - '28051039'   # ziralspiral
      - '153261993'  # sire_wiggles
      - '49882644'   # cacalac1
      - '78641303'   # patthebadger
      - '103248261'  # exogrimlocke
      - '107110706'  # savagebeartv
      - '70124234'   # compcrash
      - '63760916'   # the_rev__
